[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/bancario.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/_data/*"
  [headers.values]
    Cache-Control = "no-cache"
